version: "3"

services:
    placement-service:
        image: iivkis/micro-it-freelance_placement-service:latest
        env_file: .env
        environment:
            DB_HOST: placement-db
        depends_on:
            placement-migrate:
                condition: service_completed_successfully

    placement-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "$DB_USER", "-d", "$DB_NAME"]
            interval: 10s
            timeout: 5s
            retries: 5

    placement-migrate:
        image: migrate/migrate
        volumes:
            - ./submodules/core/migrations/placement-service:/migrations
        depends_on:
            placement-db:
                condition: service_healthy
        command:
            [
                "-path=/migrations/",
                "-database=postgres://$DB_USER:$DB_PASSWORD@placement-db/$DB_NAME?sslmode=disable",
                "up",
            ]
